"""Learner profiles, the lesson catalog, and recorded lesson results.

This package is the boundary. Import the learner interface from here, never from the
storage module underneath it -- what `__all__` names is the whole vocabulary a caller
needs, and it is what a future hosted backend has to provide.
"""

from reachy_language_tutor.learners.store import (
    get_lesson,
    get_profile,
    get_consents,
    get_progress,
    get_faceprint,
    record_result,
    forget_learner,
    record_consent,
    save_faceprint,
    delete_faceprint,
    get_lesson_content,
    store_is_available,
    get_language_catalog,
    get_enrolled_faceprints,
    get_practised_languages,
)
from reachy_language_tutor.learners.models import (
    OUTCOMES,
    DRILL_KINDS,
    CONSENT_SCOPES,
    LESSON_ORIGINS,
    RECORD_REASONS,
    CONSENT_REASONS,
    FACEPRINT_REASONS,
    CONSENT_GRANTED_BY,
    CONSENT_GRANTED_VIA,
    Drill,
    Lesson,
    Faceprint,
    UsageNote,
    DialogueTurn,
    LessonSource,
    ConsentRecord,
    LessonAttempt,
    LessonContent,
    ConsentOutcome,
    LearnerProfile,
    CatalogLanguage,
    LanguageProgress,
    PractisedLanguage,
    RecordResultOutcome,
    SaveFaceprintOutcome,
    split_catalog_by_material,
)


__all__ = [
    "CONSENT_GRANTED_BY",
    "CONSENT_GRANTED_VIA",
    "CONSENT_REASONS",
    "CONSENT_SCOPES",
    "CatalogLanguage",
    "ConsentOutcome",
    "ConsentRecord",
    "DRILL_KINDS",
    "DialogueTurn",
    "Drill",
    "FACEPRINT_REASONS",
    "Faceprint",
    "LESSON_ORIGINS",
    "LanguageProgress",
    "LearnerProfile",
    "Lesson",
    "LessonAttempt",
    "LessonContent",
    "LessonSource",
    "OUTCOMES",
    "PractisedLanguage",
    "RECORD_REASONS",
    "RecordResultOutcome",
    "record_consent",
    "SaveFaceprintOutcome",
    "UsageNote",
    "delete_faceprint",
    "forget_learner",
    "get_consents",
    "get_enrolled_faceprints",
    "get_faceprint",
    "get_language_catalog",
    "get_lesson",
    "get_lesson_content",
    "get_practised_languages",
    "get_profile",
    "get_progress",
    "record_result",
    "save_faceprint",
    "split_catalog_by_material",
    "store_is_available",
]
